name: Home Assistant Nodejs Support
description: Home Assistant Nodejs Support
version: 0.0.45
slug: hassio-addon-nodejs
startup: application
boot: auto
arch:
  - amd64
  #- aarch64
  #- armhf
  #- armv7
  #- i386
url: https://github.com/grahamj/hassio-addon-nodejs
map:
  - addon_config:rw
init: false
homeassistant_api: true
